{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE ViewPatterns #-}

module Dispatch2 where

import Yesod
import Foundation2
import Handler.Home2
import Handler.Preview

mkYesodDispatch "App" resourcesApp -- resources app was generated by mkYesodData in Foundation2
