{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

module Dispatch2 where

import Yesod
import Foundation2
import Handler.Home2

mkYesodDispatch "App" resourcesApp -- resources app was generated by mkYesodData in Foundation2
