{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

module Dispatch2 where

import Prelude
import Data.Default
import Yesod
import Yesod.Default.Util

import Foundation2

mkYesodDispatch "App" resourcesApp -- resources app was generated by mkYesodData in Foundation2

getHomeR :: Handler Html
getHomeR = defaultLayout $ do
    let filenames = ["hello.txt", "whatever.png", "hooray.jpg"] :: [String]
    setTitle "File Processor"
    $(widgetFileNoReload def "home2")
