Default: &defaults
  database: YesodSimple.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: YesodSimple_test.sqlite3
  <<: *defaults

Staging:
  database: YesodSimple_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: YesodSimple_production.sqlite3
  poolsize: 100
  <<: *defaults
